  version: '3.2'
  services:
    node:
      build: ./
      ports:
        - "3000:3000"
      depends_on:
        - mongodb_container
        - redis_container
      environment:
        MONGODB_HOST: mongodb://mongodb_container:27017
        REDIS_HOST: redis_container

    redis_container:
      image: "redis"

    mongodb_container:
      image: mongo:latest
